<a href="https://colab.research.google.com/github/pornpailinjanjit/data_viz/blob/main/More_advanced_data_structure.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

ข้อดี list เก็บได้เยอะสามารถเก็บอะไรก็ได้ \
    ง่ายกว่าเราจะใช้ list string จึงง่ายกว่า ภาษา C

### Dictionary

สามารถ index ด้วยอะไรก็ได้ แต่ลำดับจะหายไป

In [ ]:
ex_dict = {'a':10, '1':1, 'stst':5} #curly brackets ในการบอกว่าเป็น dict ตัวแรก'a'เรีกว่าkey 10 เรีกว่าvalue

In [ ]:
ex_dict['stst']

5

In [ ]:
ex2_dict = {1:'one', 2:'two', 3:'three'}

In [ ]:
ex2_dict[1]

'one'

#### การเพิ่มสมาชิก

In [ ]:
ex2_dict[0] = 'zero'

In [ ]:
ex2_dict

{0: 'zero', 1: 'one', 2: 'two', 3: 'three'}

คำสั้ง

In [ ]:
ex2_dict.keys()

dict_keys([1, 2, 3, 0])

In [ ]:
for index in ex2_dict.keys():
    print(index)

1
2
3
0


In [ ]:
ex2_dict.values()

dict_values(['one', 'two', 'three', 'zero'])

In [ ]:
index

0

ความสำคัญของ dict เอาไปใช้ร่วมกับ Dataframe ของ pandas

## Numpy Array (array n มิติ)

In [ ]:
import numpy #วิธีเรียกใช้งาน package

สร้าง numpy array

In [ ]:
ex_2d_array = numpy.array([[5.2,3.0,4.5],[9.1,0.1,0.3]])
print(ex_2d_array)

[[5.2 3.  4.5]
 [9.1 0.1 0.3]]


การชี้ค่าใน numpy array

In [ ]:
ex_2d_array[1,2]

0.3

In [ ]:
list_x = [[5.2,3.0,4.5],[9.1,0.1,0.3]] #การชี้ list


## operations

In [ ]:
ex2_2d_array = numpy.array([[1,0,0],[0,0,1]])
print(ex2_2d_array)
print(ex_2d_array)

[[1 0 0]
 [0 0 1]]
[[5.2 3.  4.5]
 [9.1 0.1 0.3]]


In [ ]:
ex_2d_array.shape #ตรวจสอบขนาดของ matrix

(2, 3)

In [ ]:
ex_2d_array + ex2_2d_array

array([[6.2, 3. , 4.5],
       [9.1, 0.1, 1.3]])

In [ ]:
list_x = [[5.2,3.0,4.5],[9.1,0.1,0.3]]
list_x2 = [[1,0,0],[0,0,1]]

list_x + list_x2

[[5.2, 3.0, 4.5], [9.1, 0.1, 0.3], [1, 0, 0], [0, 0, 1]]

In [ ]:
ex_2d_array - ex2_2d_array

array([[ 4.2,  3. ,  4.5],
       [ 9.1,  0.1, -0.7]])

In [ ]:
ex_2d_array * ex2_2d_array

array([[5.2, 0. , 0. ],
       [0. , 0. , 0.3]])

In [ ]:
print(ex_2d_array)
print(ex_2d_array.T)

[[5.2 3.  4.5]
 [9.1 0.1 0.3]]
[[5.2 9.1]
 [3.  0.1]
 [4.5 0.3]]


In [ ]:
numpy.dot(ex_2d_array,ex2_2d_array.T)

array([[5.2, 4.5],
       [9.1, 0.3]])

In [ ]:
dot_mat = numpy.dot(ex_2d_array,ex2_2d_array.T)

In [ ]:
numpy.linalg.det(dot_mat)

-39.389999999999986

search google -> stackoverflow หรือ wed ของ package สำหรับ operations อื่นๆ

### matrix slicing

In [ ]:
print(ex_2d_array)

[[5.2 3.  4.5]
 [9.1 0.1 0.3]]


In [ ]:
ex_2d_array[1,1:]

array([0.1, 0.3])

In [ ]:
ex_2d_array[:,:2]

array([[5.2, 3. ],
       [9.1, 0.1]])

HW 5 เขียน function คูณ matrix
แล้ว test กับ matrix \
(2,3)*(3,2) \
(4,4)*(4,1) \
(2,2)*(2,2) \
ส่งก่อนสอนคาบหน้า

In [ ]:
import numpy as np

In [ ]:
matrix_23 = np.array([[1,2,3],[4,5,6]])

In [ ]:
matrix_23

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
matrix_32 = np.array([[1,2],[3,4],[5,6]])

In [ ]:
matrix_32

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
matrix_44 = np.array([[1,2,3,4],[5,6,7,8],[9,8,7,6],[5,4,3,2]])

In [ ]:
matrix_44

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 8, 7, 6],
       [5, 4, 3, 2]])

In [ ]:
matrix_41 = np.array([[1],[2],[3],[4]])

In [ ]:
matrix_41

array([[1],
       [2],
       [3],
       [4]])

In [ ]:
matrix_22 = np.array([[1,2],[3,4]])

In [ ]:
matrix_22

array([[1, 2],
       [3, 4]])

In [ ]:
matrix_2_2 = np.array([[5,6],[3,4]])


In [ ]:
matrix_2_2

array([[5, 6],
       [3, 4]])

In [ ]:
 def m_matrix (A,B):
    C = [[0 for row in range(len(B[0]))] for col in range(len(A))]
    for i in range(len(A)):
        for j in range(len(B[0])):
            for k in range(len(B)):
                C[i][j] += A[i][k]*B[k][j]
    D = np.matrix(C)
    return D

In [ ]:
m_matrix(matrix_23,matrix_32) #(2,3)*(3,2)

matrix([[22, 28],
        [49, 64]])

In [ ]:
m_matrix(matrix_44,matrix_41) #(4,4)*(4,1)

matrix([[30],
        [70],
        [70],
        [30]])

In [ ]:
m_matrix(matrix_22,matrix_2_2) #(2,2)*(2,2)

matrix([[11, 14],
        [27, 34]])

#randon ,ones,zeros

zeros numpy
input มี2อย่าง จำเป็นกับไม่จำเป็น

In [1]:
import numpy as np #import numpy แล้วตั้งชื่อเป็น np

In [3]:
np.zeros(2)

array([0., 0.])

In [5]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

## ones

In [6]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

## Matrix Operation (scalar multiplication)

In [8]:
M_one = np.ones((2,3))
2*M_one

array([[2., 2., 2.],
       [2., 2., 2.]])

##random

In [9]:
np.random.rand(2,3) # uniform random [0,1)

array([[0.76130861, 0.59735313, 0.62401717],
       [0.5515312 , 0.80292887, 0.98408008]])

In [11]:
np.random.randn(2,3) # sample from normal distribution mean=0 std=1

array([[-1.16024648, -2.21203365, -0.77531919],
       [ 0.80976663,  0.64876252, -0.68843523]])

In [15]:
np.random.choice([1,2,3,'a','b','c'])

'3'

In [17]:
np.random.choice([1,2,3,28,11,100],size = 2)

array([100,  28])

In [18]:
np.random.choice([1,2,3,28,11,100],size = (2,3))

array([[100,  28,  11],
       [  2,   2, 100]])

In [19]:
np.random.choice([1,2,3,28,11,100],size = (2,3), replace=False)

array([[100,   2,   3],
       [ 11,  28,   1]])

In [21]:
np.random.choice(['A','B','C','D','F'],size=35, p= [0.1,0.2,0.4,0.29,0.01])

array(['B', 'C', 'C', 'B', 'C', 'C', 'A', 'C', 'B', 'A', 'D', 'D', 'C',
       'D', 'B', 'D', 'A', 'A', 'C', 'C', 'A', 'C', 'B', 'A', 'D', 'D',
       'D', 'B', 'D', 'D', 'C', 'C', 'B', 'A', 'C'], dtype='<U1')

#เฉลย HW Matrix Multiplication

In [34]:
def mat_mul(A,B):
    C = np.zeros((A.shape[0],B.shape[1]))#เตรียมขนาดของ matrix ผลลัพธ์
    for r_a in range(A.shape[0]):
        for c_b in range(B.shape[1]):
            for every_element in range(A.shape[1]):
                C[r_a,c_b] = C[r_a,c_b] + (A[r_a,every_element] * B[every_element,c_b])
    return C

In [28]:
mat1 = np.array([[1,2,3],[4,5,6]])
mat2 = np.array([[7,8,],[9,10],[11,12]])

In [29]:
mat_mul(mat1,mat2)

array([[ 58.,  64.],
       [139., 154.]])